server {
    listen 80;

    # Phục vụ các file tĩnh của React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Kết nối tới Backend (Spring Boot)
    # Lưu ý: 'backend' sẽ là tên service trong file docker-compose mình làm ở bước sau
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}