steps:
  # --- 1. BUILD & PUSH BACKEND ---
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/todocloud-repo/todocloud-be:${_TAG}'
      - './backend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/todocloud-repo/todocloud-be:${_TAG}'

  # --- 2. DEPLOY BACKEND ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'todocloud-be'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/todocloud-repo/todocloud-be:${_TAG}'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:asia-southeast1:todocloud-mysql'
      - '--set-env-vars'
      # Lưu ý: Điền mật khẩu SQL thật của bạn vào chỗ [PASSWORD]
      - 'CLOUD_SQL_CONNECTION_NAME=$PROJECT_ID:asia-southeast1:todocloud-mysql,DB_NAME=todo_db,DB_USER=root,DB_PASSWORD=${_DB_PASSWORD}'

images:
  - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/todocloud-repo/todocloud-be:${_TAG}"

