services:
  # 1. Backend (Spring Boot)
  backend:
    build: ./backend        # Docker sẽ tìm file Dockerfile trong thư mục backend để build
    container_name: spring-backend
    restart: always 
    environment:
      # Chỗ này Đạt lưu ý: Nếu dùng Cloud SQL thì điền IP. 
      # Nhưng IP 34.177.91.100 là IP Public, nếu máy ảo và DB cùng vùng thì nên dùng Private IP cho bảo mật nhé.
      - DB_HOST=34.177.81.199  
      - DB_NAME=todo_db
      - DB_USER=root
      - DB_PASSWORD=Ng@cdeptrai2k5
    ports:
      - "8080:8080"

  # 2. Frontend (ReactJS + Nginx)
  frontend:
    build: ./frontend       # Docker sẽ tìm file Dockerfile trong thư mục frontend để build
    container_name: react-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"