spring.application.name=todo-cloud
server.port=8080
# Cấu hình kết nối MySQL
# Khi chạy local, nó sẽ sử dụng localhost. Khi lên Docker, ta sẽ truyền biến môi trường sau.
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:todo_db}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# Hibernate cấu hình tự động tạo bảng từ code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwtSecret=dm9jYW90YW5OZ29jZGVwdHJhaWhvbkRpbmhRdW9jRGF0bmhhMTIzMTIz
app.jwtExpirationMs=86400000
