spring.application.name=todo-cloud
server.port=8080
# C?u hình k?t n?i MySQL
# Khi ch?y local, nó s? dùng localhost. Khi lên Docker, ta s? truy?n bi?n môi tr??ng sau.
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:todo_db}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# Hibernate c?u hình t? ??ng t?o b?ng t? code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
